(lang dune 3.20)
(using coq 0.10)

(generate_opam_files true)

(package
 (name rocqsat)
 (depends
  (rocq-stdlib (= 9.0.0))
  (rocq-prover (= 9.0.0))
  (rocq-core (= 9.0.1))
  (rocq-runtime (= 9.0.1))
  (rocq-equations (= 1.3.1+9.0))
  (dune (= 3.20.2))
 ))
