(lang dune 3.24)
(using rocq 0.13)

(generate_opam_files true)

(package
 (name rocqsat)
 (synopsis "A formal verification of an abstract SAT solving transition system")
 (authors "Julia Dijkstra <juliadijkstra97@gmail.com>")
 (maintainers "Julia Dijkstra <juliadijkstra97@gmail.com>")
 (homepage "https://github.com/Vlamonster/RocqSAT")
 (bug_reports "https://github.com/Vlamonster/RocqSAT/issues")
 (depends
  (rocq-stdlib (= 9.2.0))
  (rocq-prover (= 9.0.0))
  (rocq-core (= 9.3.0))
  (rocq-runtime (= 9.3.0))
  (rocq-equations (= 1.3.2+9.3))
  (dune (= 3.24.2))
 ))